### ISSUE TITLE
Meetup Workshop: Design principles & Figma best practices Part 1/3- Constructing Visual Hierarchy

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/livestream#1]
### Overview
Create a Meetup Post for Oskar's 3 part workshop series so that we can get people to attend.

### Action Items
- [x] Meetup
   - [x] Get access to meetup
   - [x] Get content from content producer (Oskar) (see [meetup guide WIP](https://docs.google.com/document/d/1HOM2GPRpEfjPGa1JM_h6767qGBJvbtxvU1UqOzpPpKo/edit?usp=sharing))
   - [x] Write Draft
   - [x] Determine if its a workshop or a seminar (it's a seminar/webinar)
   - [x] Add 580px x 320px image, custom to this workshop
   - [x] Show to Bonnie
      - [x] Add additional information required
      - [x] Show to bonnie again.
- [x] Zoom
    - [x] Bonnie Setup Zoom link for event
- [x] Meetup 
    - [x] Bonnie publishes event on meetup and uses Announce option (future versions of workshop to be published by Harsh.
- [x] Slack
   - [x] Write post for slack announcement (Harsh)
      - [x] must be short
      - [x] have emojis and be fun
      - [x] drive signups for the meetup and joins to the community of practice channel (in this case ui-ux) - Currently has 124 members
   - [ ] Slack Admin (Bonnie & Olivia) publishes an announcement in our Slack community general channel 
- [x] Meetup
   - [x] Write a note that Bonnie will send on Meetup the day before the event that will contain:
      - [x] The Hack for LA community looks forward to hosting the [insert details about the webinar].
      - [x]  The Webinar lead will be taking questions from the attendees, please read our code of conduct before attending (https://hackforla.org/conduct).
      - [x]  the zoom link for the meeting has changed and the correct link can be found on the meetup page for the event: https://www.meetup.com/hackforla/events/276241362/

### Resources/Instructions
- [Meetup Draft](https://www.meetup.com/hackforla/events/276241362/)
- [Previous Approved Meetups](https://github.com/hackforla/livestream/projects/2#card-54436467)
- [Some bios - a bit long for this but you get the idea](https://github.com/100Automations/Website/issues/62#issuecomment-761694853)

**Comment by ExperimentsInHonesty** [comment]
~@Oskar-Adam-Zloch We need a revised Bio.  @vharsh25 @Olivia-Chiong will help.~

Olivia wrote the bio below:

**Comment by Olivia-Chiong** [comment]
Oskar builds products to delight users. A former artist and graphic designer turned experience designer, he is currently focused on spreading good experience design methodologies by sharing his knowledge via workshops at Hack for LA.

**Comment by ExperimentsInHonesty** [comment]
Image for meetup is supposed to be 580px x 320px

**Comment by Oskar-Potratz-Zloch** [comment]
I've added the cover image for the event on Meetup.
I am open to hear Your feedback.

**Comment by ExperimentsInHonesty** [comment]
@Oskar-Adam-Zloch the image is perfect!  

@vharsh25 I have made my final edits to the meetup post and published/announced it (announcements go out to Hack for LA's 5,167 members).  I will also @channel it from the Hack for LA slack today
![meetup-oskar 1:3 figma and design seminar series](https://user-images.githubusercontent.com/37763229/107415220-f36d6100-6ac7-11eb-9ad7-c39a7703c142.png)

**Comment by ExperimentsInHonesty** [comment]
@Oskar-Adam-Zloch @vharsh25 I updated the zoom link on the meetup.  Here are the settings for the meeting: 
![screencapture-zoom-us-meeting-87238524137-2021-02-09-11_13_19](https://user-images.githubusercontent.com/37763229/107415175-e5b7db80-6ac7-11eb-9458-d5acc6cf675b.png)

**Comment by ExperimentsInHonesty** [comment]
@Oskar-Adam-Zloch questions:
1. How long is this event?
2. Are you going to take questions
2. if yes, how long?

**Comment by Oskar-Potratz-Zloch** [comment]
@ExperimentsInHonesty 

Event is going to take 1.5h
I will try to fit everything in 1h and use the rest 30min for questions

**Comment by ExperimentsInHonesty** [comment]
@Oskar-Adam-Zloch So more seminar than workshop, yes?  Or will they be doing any tasks?
workshop = you instruct and they practice
seminar or webinar = you speak/demo, etc -and they watch and take notes / ask questions (edited)

**Comment by ExperimentsInHonesty** [comment]
Oskar says seminar to the above question

**Comment by Oskar-Potratz-Zloch** [comment]
It will be a seminar, with no tasks

**Comment by ExperimentsInHonesty** [comment]
I revised the meetup to change it from workshop series to Webinar with Q&A (screenshot below). 

![screencapture-meetup-hackforla-events-276241362-2021-02-09-11_52_25](https://user-images.githubusercontent.com/37763229/107420041-51e90e00-6acd-11eb-8551-3251ea6f10d4.png)

**Comment by ExperimentsInHonesty** [comment]
I updated the zoom meeting info (see screenshot below).
![screencapture-zoom-us-meeting-87238524137-2021-02-09-11_55_42](https://user-images.githubusercontent.com/37763229/107420482-c8860b80-6acd-11eb-996d-ce62fd4ed0aa.png)

**Comment by ExperimentsInHonesty** [comment]
FYI: @Olivia-Chiong @vharsh25 If later we decide we want to make seminars like these into traditional webinars so that people can only be seen when we call on them etc, then we have to pay $40 a month to add it to our current account level
